import React, { useEffect, useState } from 'react';
import { OpsHeader } from '../components/common/OperationsUI';
import './OperationsPages.css';
const key = 'aeroground-settings-v1';
const defaults = { airport:'AeroGround Demo Airport',terminal:'Terminal 1',timezone:'Asia/Singapore',maintenanceReminder:true,criticalFaultAlert:true,inspectionReminder:true };
export default function SettingsPage() {
  const [values,setValues] = useState(() => {try{return {...defaults,...JSON.parse(localStorage.getItem(key))};}catch{return defaults;}});
  const [saved,setSaved] = useState(false);
  useEffect(() => {localStorage.setItem(key,JSON.stringify(values));},[values]);
  const change = (field,value) => {setValues(v => ({...v,[field]:value}));setSaved(false);};
  return <div className="ops-page"><OpsHeader title="System Settings" subtitle="Configure this browser's AeroGround prototype preferences." action={<button className="btn-primary" onClick={() => setSaved(true)}>Save settings</button>}/>{saved && <div className="ops-toast" role="status">Settings saved in this browser.</div>}<div className="ops-grid"><section className="aeroground-card ops-card"><div className="ops-section-head"><h2>Airport information</h2></div><div className="ops-form"><label className="ops-field full">Airport name<input className="form-input" value={values.airport} onChange={e => change('airport',e.target.value)}/></label><label className="ops-field">Terminal<input className="form-input" value={values.terminal} onChange={e => change('terminal',e.target.value)}/></label><label className="ops-field">Timezone<input className="form-input" value={values.timezone} onChange={e => change('timezone',e.target.value)}/></label></div></section><section className="aeroground-card ops-card"><div className="ops-section-head"><h2>Notification preferences</h2></div>{[['maintenanceReminder','Maintenance due reminders'],['criticalFaultAlert','Critical fault alerts'],['inspectionReminder','Inspection overdue reminders']].map(([key,label]) => <label className="ops-settings-row" key={key}><span><strong>{label}</strong><small>Show this alert category when notifications are connected</small></span><input type="checkbox" checked={values[key]} onChange={e => change(key,e.target.checked)}/></label>)}</section><section className="aeroground-card ops-card"><h2>Configured categories</h2><p className="ops-note">Equipment: Pushback Tug, Ground Power, Belt Loader, Baggage Tractor, Passenger Bus, Catering Truck, Air Start Unit, Potable / Lavatory Truck.</p><p className="ops-note">Maintenance: Preventive, Corrective, Inspection. Faults: Hydraulic, Electrical, Mechanical, Brakes, Tyres, Engine, Battery, Safety Equipment, Other.</p></section><section className="aeroground-card ops-card"><h2>Prototype system status</h2><div className="ops-settings-row"><span>Frontend</span><strong>React / Vite</strong></div><div className="ops-settings-row"><span>Record storage</span><strong>Browser localStorage</strong></div><div className="ops-settings-row"><span>Database</span><strong>Not connected</strong></div></section></div></div>;
}
